import { useState, useEffect } from "react";
import Filter from "../filter/Filter";
import SearchBar from "../search/SearchBar";
import JobOptions from "./leftPannel/JobOptions";
import JobView from "../../components/jobs/rightPannel/JobView";

import ModalComp from "../modal/ModalComp";
import { MdEdit } from "react-icons/md";

const MainJobContainer = () => {
  const jobData = [
    {
      id: "1",
      logo: "globant",
      segment: "Technical",
      status: "LIVE",
      title: "React JS Freelancer",
      companyName: "Triveous",
      impressions: "5421 Impressions",
      deadline: "15 Feb 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Globant is hiring for the role of React JS Freelancer!",
      responsibilities: [
        "Developing user interfaces for web applications using React.js",
        "Building reusable components and front-end libraries for future use",
        "Translating designs and wireframes into high-quality code",
        "Optimizing components for maximum performance across a vast array of web-capable devices and browsers",
        "Staying updated on emerging trends and technologies in front-end development",
        "Participating in code reviews to maintain code quality standards",
        "Contributing to the continuous improvement of development processes and tools",
        "Mentoring junior developers and providing technical guidance",
        "Collaborating with UX/UI designers to implement visual elements and user interactions",
      ],

      requirements: [
        "Bachelor’s degree in Computer Science or related field",
        "Proven experience as a React.js Developer",
        "Strong proficiency in JavaScript, HTML, and CSS",
        "Experience with popular React.js workflows (such as Redux)",
        "Familiarity with RESTful APIs and modern front-end build pipelines",
        "Knowledge of modern authorization mechanisms, such as JSON Web Token",
        "Experience with common front-end development tools such as Babel, Webpack, NPM, etc.",
        "A keen eye for UI/UX design and attention to detail",
        "Excellent problem-solving and debugging skills",
        "Good understanding of browser rendering behavior and performance",
        "Ability to work independently and collaborate with cross-functional teams",
      ],
    },
    {
      id: "2",
      logo: "itworks",
      segment: "Technical",
      status: "LIVE",
      title: "Web UI Developer (React)",
      companyName: "ITWorks Infotech Pvt. Ltd",
      impressions: "7568 Impressions",
      deadline: "15 jan 2024",
      hashtags: ["#Web Development", "#Programmimg"],
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      jobDescription:
        "Triveous is hiring for the role of Web UI Developer (React)",
      requirements: [
        "Bachelor’s degree in Computer Science, Web Development, or related field",
        "Proven experience as a Web UI Developer or similar role",
        "Strong proficiency in HTML, CSS, and JavaScript",
        "Experience with front-end frameworks such as React.js or Angular",
        "Knowledge of responsive design principles and cross-browser compatibility",
        "Familiarity with version control systems (e.g., Git)",
        "Strong communication and interpersonal skills",
        "Continuous learning mindset to stay updated on the latest industry trends",
      ],
      responsibilities: [
        "Developing and maintaining user interfaces for web applications",
        "Collaborating with UX/UI designers to translate design concepts into functional and visually appealing interfaces",
        "Ensuring the technical feasibility of UI/UX designs",
        "Optimizing applications for maximum speed and scalability",
        "Implementing and maintaining front-end components and libraries",
        "Collaborating with back-end developers to integrate user-facing elements with server-side logic",
        "Conducting thorough code reviews to maintain code quality standards",
        "Providing mentorship and guidance to junior developers",
        "Contributing to the continuous improvement of development processes and tools",
      ],
    },
    {
      id: "3",
      logo: "hsbc",
      segment: "Technical",
      status: "LIVE",
      title: "React Native Developer",
      companyName: "Globant",
      hashtags: ["#Web Development", "#Programmimg"],
      impressions: "2876 Impressions",
      deadline: "24 jan 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      jobDescription: "HSBC is hiring for the role of React Native Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Web Development, or related field",
        "Proven experience as a React Native Developer",
        "Strong proficiency in JavaScript and React Native framework",
        "Familiarity with mobile app development best practices and patterns",
        "Experience with debugging and performance optimization for mobile applications",
        "Strong problem-solving skills",
      ],

      responsibilities: [
        "Develop and maintain mobile applications using React Native",
        "Collaborate with cross-functional teams to define and implement app features",
        "Ensure the performance, quality, and responsiveness of applications",
        "Debug and resolve issues related to mobile app development",
        "Stay updated on the latest trends and technologies in mobile app development",
        "Contribute to the continuous improvement of mobile development processes",
      ],
    },
    {
      id: "4",
      logo: "togoteams",
      segment: "Technical",
      status: "LIVE",
      title: ".Net Developer",
      companyName: "HSBC",
      impressions: "3999 Impressions",
      deadline: "10 Feb 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Togoteams is hiring for the role of .Net Developer",
      requirements: [
        "Bachelor’s degree in Computer Science or a related field",
        "Proven experience as a Lead .Net Developer",
        "Expertise in .Net framework and C# programming language",
        "Experience with ASP.NET MVC and Web API development",
        "Strong knowledge of database systems, SQL, and ORM technologies",
        "Experience with front-end technologies such as HTML, CSS, and JavaScript",
        "Understanding of software architecture and design principles",
        "Leadership and team management skills",
        "Excellent problem-solving and debugging abilities",
        "Effective communication and interpersonal skills",
        "Continuous learning mindset to stay updated on industry trends",
      ],

      responsibilities: [
        "Lead and mentor a team of .Net Developers",
        "Design and develop robust and scalable .Net applications",
        "Collaborate with stakeholders to gather and analyze requirements",
        "Ensure code quality and adherence to coding standards",
        "Optimize application performance and troubleshoot issues",
        "Conduct code reviews and provide constructive feedback",
        "Participate in architectural decisions and system design",
        "Coordinate with cross-functional teams for project delivery",
        "Stay updated on emerging technologies and best practices",
        "Contribute to the continuous improvement of development processes",
      ],
    },
    {
      id: "5",
      logo: "itworks",
      segment: "Technical",
      status: "LIVE",
      title: "Pyhon Developer",
      companyName: "Togo Teams",
      impressions: "6245 Impressions",
      deadline: "10 jan 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "ITworks is hiring for the role of Python Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as a Python Developer",
        "Strong proficiency in Python programming language",
        "Experience with web frameworks such as Django or Flask",
        "Knowledge of front-end technologies including HTML, CSS, and JavaScript",
        "Familiarity with database systems, SQL, and ORM technologies",
        "Understanding of software development best practices and design patterns",
        "Problem-solving and debugging skills",
        "Excellent communication and collaboration abilities",
        "Continuous learning mindset to stay updated on industry trends",
      ],

      responsibilities: [
        "Design and develop scalable and maintainable Python applications",
        "Collaborate with cross-functional teams to define and implement features",
        "Integrate user-facing elements using server-side logic",
        "Ensure the performance, quality, and responsiveness of applications",
        "Troubleshoot and resolve issues related to Python development",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and implement security measures",
        "Participate in system architecture and design decisions",
        "Stay updated on emerging technologies and best practices in Python development",
        "Contribute to the continuous improvement of development processes",
      ],
    },
    {
      id: "6",
      logo: "globant",
      segment: "Technical",
      status: "LIVE",
      title: "Software Developer",
      companyName: "Globant",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      impressions: "8791 Impressions",
      deadline: "31 Dec 2023",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Globant is hiring for the role of Software Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as a Software Developer",
        "Strong proficiency in one or more programming languages (e.g., Java, C++, Python)",
        "Knowledge of software development best practices and design patterns",
        "Experience with web or mobile application development",
        "Familiarity with front-end and back-end technologies",
        "Understanding of database systems, SQL, and version control systems",
        "Excellent problem-solving and debugging skills",
        "Strong analytical and communication abilities",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on industry trends",
      ],

      responsibilities: [
        "Design, code, and test software applications",
        "Collaborate with cross-functional teams to define and implement features",
        "Participate in system architecture and design decisions",
        "Troubleshoot and resolve software-related issues",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and implement security measures",
        "Integrate software components and third-party libraries",
        "Stay updated on emerging technologies and best practices in software development",
        "Contribute to the continuous improvement of development processes",
        "Document software designs, coding, and testing activities",
      ],
    },
    {
      id: "7",
      logo: "triveous",
      segment: "Technical",
      status: "LIVE",
      title: "Java Developer",
      companyName: "HSBC",
      impressions: "4321 Impressions",
      deadline: "1 Feb 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Triveous is hiring for the role of Java Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as a Java Developer",
        "Strong proficiency in Java programming language",
        "Experience with Spring Framework and related technologies",
        "Knowledge of web application development and RESTful APIs",
        "Understanding of database systems, SQL, and ORM technologies",
        "Familiarity with front-end technologies including HTML, CSS, and JavaScript",
        "Excellent problem-solving and debugging skills",
        "Strong analytical and communication abilities",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on industry trends",
      ],

      responsibilities: [
        "Design and develop high-quality, scalable Java applications",
        "Collaborate with cross-functional teams to define and implement features",
        "Participate in system architecture and design decisions",
        "Troubleshoot and resolve Java-related issues",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and implement security measures",
        "Integrate software components and third-party libraries",
        "Stay updated on emerging technologies and best practices in Java development",
        "Contribute to the continuous improvement of development processes",
        "Document software designs, coding, and testing activities",
      ],
    },
    {
      id: "8",
      logo: "realTtech",
      segment: "Technical",
      status: "LIVE",
      title: "Fullstack Developer",
      companyName: "ITWorks Infotech Pvt. Ltd",
      impressions: "5566 Impressions",
      deadline: "9 jan 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Reacltech is hiring for the role of Fullstack Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as a Fullstack Developer",
        "Strong proficiency in front-end technologies such as HTML, CSS, and JavaScript",
        "Experience with front-end frameworks/libraries (e.g., React, Angular, Vue)",
        "Solid understanding of back-end technologies and server-side languages (e.g., Node.js, Python, Java)",
        "Knowledge of database systems, SQL, and ORM technologies",
        "Familiarity with version control systems (e.g., Git)",
        "Excellent problem-solving and debugging skills",
        "Strong analytical and communication abilities",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on industry trends",
      ],

      responsibilities: [
        "Design and develop both front-end and back-end components of applications",
        "Collaborate with cross-functional teams to define and implement features",
        "Participate in system architecture and design decisions",
        "Troubleshoot and resolve issues related to full-stack development",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and implement security measures",
        "Integrate software components and third-party libraries",
        "Stay updated on emerging technologies and best practices in full-stack development",
        "Contribute to the continuous improvement of development processes",
        "Document software designs, coding, and testing activities",
      ],
    },
    {
      id: "9",
      logo: "google",
      segment: "Technical",
      status: "LIVE",
      title: "Angular Developer",
      companyName: "Google",
      impressions: "9876 Impressions",
      deadline: "6 Feb 2024",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Google is hiring for the role of Angular Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as an Angular Developer",
        "Strong proficiency in TypeScript and JavaScript",
        "Experience with Angular framework and related technologies",
        "Knowledge of HTML, CSS, and front-end development best practices",
        "Understanding of web application development and RESTful APIs",
        "Familiarity with version control systems (e.g., Git)",
        "Excellent problem-solving and debugging skills",
        "Strong analytical and communication abilities",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on industry trends",
      ],

      responsibilities: [
        "Design and develop high-quality, scalable Angular applications",
        "Collaborate with cross-functional teams to define and implement features",
        "Participate in system architecture and design decisions",
        "Troubleshoot and resolve Angular-related issues",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and implement security measures",
        "Integrate software components and third-party libraries",
        "Stay updated on emerging technologies and best practices in Angular development",
        "Contribute to the continuous improvement of development processes",
        "Document software designs, coding, and testing activities",
      ],
    },
    {
      id: "10",
      logo: "amazon",
      segment: "Technical",
      status: "LIVE",
      title: "Machine Learning Engineer",
      companyName: "Amazon",
      impressions: "6543 Impressions",
      deadline: "15 Days Left",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "Amazon is hiring for the role of Machine Learning Engineer",
      requirements: [
        "Master’s or Ph.D. degree in Computer Science, Machine Learning, or a related field",
        "Proven experience as a Machine Learning Engineer or Data Scientist",
        "Strong proficiency in programming languages such as Python or R",
        "In-depth knowledge of machine learning frameworks and libraries (e.g., TensorFlow, PyTorch)",
        "Experience with data preprocessing, feature engineering, and model evaluation",
        "Understanding of various machine learning algorithms and techniques",
        "Familiarity with big data technologies and distributed computing (e.g., Spark)",
        "Knowledge of deep learning architectures and neural networks",
        "Strong problem-solving and analytical skills",
        "Effective communication and collaboration abilities",
        "Continuous learning mindset to stay updated on advancements in machine learning",
      ],

      responsibilities: [
        "Design and implement machine learning models and algorithms",
        "Collect, preprocess, and analyze large datasets to derive insights",
        "Collaborate with cross-functional teams to integrate machine learning solutions into applications",
        "Optimize and fine-tune machine learning models for performance and accuracy",
        "Stay updated on the latest developments in machine learning and artificial intelligence",
        "Contribute to the development of tools and frameworks for machine learning",
        "Communicate complex technical concepts to non-technical stakeholders",
        "Collaborate with data engineers to ensure data availability and quality",
        "Participate in the continuous improvement of machine learning processes",
        "Document machine learning models, experiments, and findings",
      ],
    },
    {
      id: "11",
      logo: "microsoft",
      segment: "Technical",
      status: "LIVE",
      title: "DevOps Specialist",
      companyName: "Microsoft",
      hashtags: ["#Web Development", "#Programmimg"],
      impressions: "7890 Impressions",
      deadline: "8 Days Left",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      jobDescription: "Microsoft is hiring for the role of DevOps Specialist",
      requirements: [
        "Bachelor’s degree in Computer Science, Information Technology, or a related field",
        "Proven experience as a DevOps Specialist or similar role",
        "Strong proficiency in scripting languages (e.g., Shell, Python, Ruby)",
        "Experience with configuration management tools (e.g., Ansible, Puppet)",
        "Knowledge of containerization and orchestration tools (e.g., Docker, Kubernetes)",
        "Understanding of continuous integration and continuous delivery (CI/CD) pipelines",
        "Familiarity with version control systems (e.g., Git)",
        "Experience with cloud platforms (e.g., AWS, Azure, GCP)",
        "Knowledge of infrastructure as code (IaC) principles",
        "Strong problem-solving and troubleshooting skills",
        "Effective communication and collaboration abilities",
        "Continuous learning mindset to stay updated on DevOps practices and tools",
      ],

      responsibilities: [
        "Design and implement CI/CD pipelines for software delivery",
        "Automate and streamline deployment, monitoring, and infrastructure management processes",
        "Collaborate with development and operations teams to ensure smooth production deployments",
        "Implement and manage infrastructure as code (IaC) solutions",
        "Configure and maintain cloud infrastructure and services",
        "Troubleshoot and resolve issues related to infrastructure and deployments",
        "Implement and manage monitoring and alerting systems",
        "Collaborate with cross-functional teams to improve DevOps processes",
        "Stay updated on emerging technologies and best practices in DevOps",
        "Contribute to the documentation of DevOps processes and configurations",
      ],
    },
    {
      id: "12",
      logo: "apple",
      segment: "Technical",
      status: "LIVE",
      title: "iOS App Developer",
      companyName: "Apple Inc.",
      impressions: "5432 Impressions",
      deadline: "20 Days Left",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription: "Apple is hiring for the role of iOS App Developer",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as an iOS App Developer",
        "Strong proficiency in Swift programming language",
        "Experience with iOS SDK and frameworks",
        "Knowledge of mobile app architecture and design patterns",
        "Understanding of iOS human interface guidelines",
        "Familiarity with version control systems (e.g., Git)",
        "Experience with RESTful APIs and integrating third-party libraries",
        "Strong problem-solving and debugging skills",
        "Attention to detail and a passion for creating user-friendly interfaces",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on iOS development trends",
      ],

      responsibilities: [
        "Design and develop high-quality iOS applications",
        "Collaborate with cross-functional teams to define and implement features",
        "Participate in app architecture and design decisions",
        "Troubleshoot and resolve iOS-related issues",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and ensure responsiveness",
        "Integrate software components and third-party libraries",
        "Stay updated on emerging technologies and best practices in iOS development",
        "Contribute to the continuous improvement of development processes",
        "Document software designs, coding, and testing activities",
      ],
    },
    {
      id: "13",
      logo: "facebook",
      segment: "Technical",
      status: "LIVE",
      title: "Frontend Developer (React)",
      companyName: "Meta (Facebook)",
      impressions: "8765 Impressions",
      deadline: "12 Days Left",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "facebook is hiring for the role of Frontend Developer (React)",
      requirements: [
        "Bachelor’s degree in Computer Science, Software Engineering, or a related field",
        "Proven experience as a Frontend Developer with expertise in React.js",
        "Strong proficiency in HTML, CSS, and JavaScript",
        "Experience with state management libraries (e.g., Redux)",
        "Knowledge of modern frontend build pipelines and tools",
        "Understanding of web performance optimization techniques",
        "Familiarity with version control systems (e.g., Git)",
        "Experience with RESTful APIs and integrating third-party libraries",
        "Strong problem-solving and debugging skills",
        "Attention to detail and a passion for creating visually appealing interfaces",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on frontend development trends",
      ],

      responsibilities: [
        "Design and develop user interfaces using React.js",
        "Collaborate with UX/UI designers to implement design specifications",
        "Participate in system architecture and design decisions",
        "Troubleshoot and resolve frontend-related issues",
        "Conduct code reviews and provide constructive feedback",
        "Optimize application performance and ensure responsiveness",
        "Integrate software components and third-party libraries",
        "Stay updated on emerging technologies and best practices in frontend development",
        "Contribute to the continuous improvement of development processes",
        "Document software designs, coding, and testing activities",
      ],
    },
    {
      id: "14",
      logo: "company1",
      title: "Marketing Specialist",
      companyName: "Global Marketing Solutions",
      impressions: "1234 Impressions",
      deadline: "15 Days Left",
      segment: "Non-Technical",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      status: "LIVE",
      jobDescription:
        "Global Marketing Solutions is hiring for the role of Marketing Specialist",
      responsibilities: [
        "Plan and execute marketing campaigns across various channels",
        "Analyze and report on marketing performance metrics",
        "Collaborate with internal teams to create landing pages and optimize user experience",
      ],
      requirements: [
        "Bachelor’s degree in Marketing or related field",
        "Proven experience in developing and implementing marketing strategies",
        "Strong analytical and project management skills",
      ],
    },
    {
      id: "15",
      logo: "company2",
      title: "Financial Analyst",
      companyName: "Dynamic Financial Services",
      impressions: "5678 Impressions",
      deadline: "10 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "Dynamic Financial Services is hiring for the role of Financial Analyst",
      requirements: [
        "Bachelor’s degree in Finance, Accounting, Economics, or a related field",
        "Proven experience as a Financial Analyst or similar role",
        "Strong proficiency in financial modeling and analysis",
        "Knowledge of accounting principles and financial reporting",
        "Experience with financial forecasting and budgeting",
        "Analytical mindset with attention to detail",
        "Excellent quantitative and qualitative analysis skills",
        "Proficiency in spreadsheet software (e.g., Microsoft Excel)",
        "Effective communication and presentation abilities",
        "Ability to work collaboratively in a team environment",
        "Continuous learning mindset to stay updated on financial trends",
      ],

      responsibilities: [
        "Conduct financial analysis and provide insights for decision-making",
        "Prepare financial reports, budgets, and forecasts",
        "Evaluate and recommend financial strategies and solutions",
        "Assess and monitor financial performance against targets",
        "Analyze market trends and industry competitors",
        "Collaborate with cross-functional teams on financial matters",
        "Present financial findings to stakeholders and leadership",
        "Contribute to the development of financial policies and procedures",
        "Ensure compliance with financial regulations and standards",
        "Participate in financial audits and reviews",
      ],
    },
    {
      id: "16",
      logo: "company3",
      title: "Human Resources Manager",
      companyName: "PeopleHub Solutions Inc.",
      impressions: "4321 Impressions",
      deadline: "12 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "PeopleHub Solutions Inc. is hiring for the role of Human Resources Manager",
      requirements: [
        "Bachelor’s degree in Human Resources, Business Administration, or a related field",
        "Proven experience as a Human Resources Manager or similar role",
        "In-depth knowledge of human resources principles and practices",
        "Experience with HRIS (Human Resources Information System) software",
        "Strong understanding of employment laws and regulations",
        "Excellent interpersonal and communication skills",
        "Ability to handle confidential information with discretion",
        "Organizational and multitasking abilities",
        "Problem-solving and conflict resolution skills",
        "Strong leadership and people management skills",
        "Continuous learning mindset to stay updated on HR trends",
      ],

      responsibilities: [
        "Develop and implement HR strategies and initiatives aligned with company goals",
        "Oversee the recruitment and selection process",
        "Manage employee relations, including conflict resolution",
        "Administer and maintain HRIS systems and records",
        "Ensure compliance with employment laws and regulations",
        "Coordinate employee training and development programs",
        "Conduct performance management and appraisal processes",
        "Handle employee grievances and disciplinary actions",
        "Develop and implement workplace policies and procedures",
        "Collaborate with management to address human resources issues",
      ],
    },
    {
      id: "17",
      logo: "company4",
      title: "Sales Representative",
      companyName: "Global Sales Co.",
      impressions: "8765 Impressions",
      deadline: "18 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "Global Sales Co. is hiring for the role of Sales Representative",
      requirements: [
        "Bachelor’s degree in Business, Marketing, or a related field (preferred)",
        "Proven experience as a Sales Representative or similar role",
        "Excellent communication and interpersonal skills",
        "Strong negotiation and persuasion abilities",
        "Customer-focused with a positive and energetic attitude",
        "Ability to build and maintain client relationships",
        "Knowledge of sales principles and techniques",
        "Organizational and time-management skills",
        "Results-oriented with a track record of meeting sales targets",
        "Familiarity with CRM (Customer Relationship Management) software",
        "Continuous learning mindset to stay updated on sales trends",
      ],

      responsibilities: [
        "Identify and qualify leads through various channels",
        "Conduct sales presentations and product demonstrations",
        "Negotiate contracts and terms with clients",
        "Build and maintain strong relationships with clients",
        "Achieve and exceed sales targets and objectives",
        "Collaborate with the sales team to develop strategies",
        "Provide accurate and timely sales reports",
        "Stay updated on industry trends and competitor activities",
        "Participate in sales training and professional development",
        "Contribute to the improvement of sales processes",
      ],
    },
    {
      id: "18",
      logo: "company5",
      title: "Customer Service Specialist",
      companyName: "ServiceFirst Ltd.",
      impressions: "9876 Impressions",
      deadline: "7 Days Left",
      segment: "Non-Technical",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      status: "LIVE",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "ServiceFirst Ltd. is hiring for the role of Customer Service Specialist",
      requirements: [
        "High school diploma or equivalent (Bachelor’s degree preferred)",
        "Proven experience as a Customer Service Specialist or similar role",
        "Excellent communication and problem-solving skills",
        "Customer-focused with a positive and empathetic attitude",
        "Strong multitasking and organizational abilities",
        "Ability to handle challenging customer situations with professionalism",
        "Familiarity with customer service software and systems",
        "Team-oriented with the ability to work collaboratively",
        "Attention to detail and accuracy in handling customer information",
        "Time-management skills to meet service level agreements",
        "Continuous learning mindset to stay updated on customer service best practices",
      ],

      responsibilities: [
        "Respond to customer inquiries via phone, email, or chat",
        "Provide information and assistance to customers",
        "Resolve customer issues and complaints in a timely manner",
        "Handle customer escalations and collaborate with other teams",
        "Maintain accurate records of customer interactions and transactions",
        "Coordinate with internal departments to address customer needs",
        "Process orders, returns, and exchanges",
        "Assist customers with product or service-related questions",
        "Stay updated on company products, services, and policies",
        "Contribute to the improvement of customer service processes",
      ],
    },
    {
      id: "19",
      logo: "company6",
      title: "Event Coordinator",
      companyName: "EventPros Unlimited",
      impressions: "3456 Impressions",
      deadline: "22 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "EventPros Unlimited is hiring for the role of Event Coordinator",
      requirements: [
        "Bachelor’s degree in Event Management, Marketing, or a related field",
        "Proven experience as an Event Coordinator or similar role",
        "Strong organizational and multitasking skills",
        "Excellent communication and interpersonal abilities",
        "Creative and detail-oriented with an eye for design",
        "Ability to work well under pressure and meet tight deadlines",
        "Familiarity with event planning software and tools",
        "Negotiation and vendor management skills",
        "Team-oriented with the ability to work collaboratively",
        "Flexibility to work evenings and weekends as required",
        "Continuous learning mindset to stay updated on event industry trends",
      ],

      responsibilities: [
        "Plan and organize events from conception to completion",
        "Coordinate logistics, including venue selection, catering, and transportation",
        "Collaborate with clients to understand event requirements",
        "Negotiate contracts with vendors and suppliers",
        "Manage event budgets and financial transactions",
        "Supervise event setup, execution, and breakdown",
        "Coordinate with internal teams to ensure seamless event delivery",
        "Address and resolve issues that may arise during events",
        "Stay updated on industry trends and innovative event concepts",
        "Contribute to the improvement of event planning processes",
      ],
    },
    {
      id: "20",
      logo: "company7",
      title: "Graphic Designer",
      companyName: "Creative Designs Studio",
      impressions: "6543 Impressions",
      deadline: "14 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "Creative Designs Studio is hiring for the role of Graphic Designer",
      requirements: [
        "Bachelor’s degree in Graphic Design or a related field",
        "Proven experience as a Graphic Designer or similar role",
        "Proficiency in graphic design software (e.g., Adobe Creative Suite)",
        "Strong portfolio showcasing creative and visually appealing designs",
        "Knowledge of design principles, color theory, and typography",
        "Attention to detail and ability to work within brand guidelines",
        "Excellent communication and collaboration skills",
        "Ability to meet deadlines and manage multiple projects simultaneously",
        "Understanding of print and digital design processes",
        "Continuous learning mindset to stay updated on design trends",
      ],

      responsibilities: [
        "Create visually engaging graphics and illustrations",
        "Collaborate with clients or internal teams to understand design requirements",
        "Develop and present design concepts and proposals",
        "Produce high-quality design deliverables for print and digital media",
        "Ensure consistency in brand identity across various platforms",
        "Review and provide feedback on design work from team members",
        "Stay updated on industry trends and design innovations",
        "Collaborate with printers and vendors for production",
        "Maintain an organized archive of design assets and files",
        "Contribute to the improvement of design processes and workflows",
      ],
    },
    {
      id: "21",
      logo: "company8",
      title: "Administrative Assistant",
      companyName: "AdminPro Solutions",
      impressions: "7890 Impressions",
      deadline: "11 Days Left",
      segment: "Non-Technical",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      status: "LIVE",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "AdminPro Solutions Studio is hiring for the role of Administrative Assistant",
    },
    {
      id: "22",
      logo: "company9",
      title: "Healthcare Administrator",
      companyName: "Health Solutions Inc.",
      impressions: "5432 Impressions",
      deadline: "20 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "Health Solutions Inc. Studio is hiring for the role of Healthcare Administrator",
      requirements: [
        "High school diploma or equivalent (Associate’s or Bachelor’s degree preferred)",
        "Proven experience as an Administrative Assistant or similar role",
        "Proficiency in office software (e.g., Microsoft Office Suite)",
        "Strong organizational and multitasking skills",
        "Excellent communication and interpersonal abilities",
        "Attention to detail and accuracy in handling administrative tasks",
        "Ability to handle confidential information with discretion",
        "Time-management skills to meet deadlines",
        "Team-oriented with the ability to work collaboratively",
        "Customer service mindset with a positive and proactive attitude",
        "Continuous learning mindset to stay updated on office tools and practices",
      ],

      responsibilities: [
        "Provide administrative support to ensure efficient office operations",
        "Handle incoming calls, emails, and other communications",
        "Coordinate and schedule appointments, meetings, and travel arrangements",
        "Maintain and organize filing systems, records, and documentation",
        "Assist with the preparation of reports and presentations",
        "Manage office supplies and equipment",
        "Greet and assist visitors in a professional and courteous manner",
        "Handle general clerical tasks, such as data entry and photocopying",
        "Assist in the coordination of special events or projects",
        "Contribute to the improvement of administrative processes",
      ],
    },
    {
      id: "23",
      logo: "company10",
      title: "Education Coordinator",
      companyName: "EduPro Academy",
      impressions: "8765 Impressions",
      deadline: "9 Days Left",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      segment: "Non-Technical",
      status: "LIVE",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "EduPro Academy Studio is hiring for the role of Education Coordinator",
      requirements: [
        "Bachelor’s degree in Education, Human Resources, or a related field",
        "Proven experience as an Education Coordinator or similar role",
        "Knowledge of educational principles and curriculum development",
        "Strong organizational and multitasking skills",
        "Excellent communication and interpersonal abilities",
        "Ability to develop and deliver training programs",
        "Familiarity with learning management systems (LMS)",
        "Attention to detail and accuracy in handling educational materials",
        "Team-oriented with the ability to work collaboratively",
        "Continuous learning mindset to stay updated on education trends",
      ],

      responsibilities: [
        "Coordinate and implement educational programs and initiatives",
        "Develop and update educational curriculum and materials",
        "Facilitate training sessions for educators and staff",
        "Evaluate the effectiveness of educational programs",
        "Collaborate with schools, teachers, and educational partners",
        "Provide guidance and support to educators on curriculum implementation",
        "Maintain records of educational activities and participant progress",
        "Assist in the development of educational policies and procedures",
        "Stay updated on industry trends and innovations in education",
        "Contribute to the improvement of educational processes",
      ],
    },
    {
      id: "24",
      logo: "company11",
      title: "Executive Assistant",
      companyName: "Executive Services Ltd.",
      impressions: "4321 Impressions",
      deadline: "13 Days Left",
      segment: "Non-Technical",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      status: "LIVE",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "Executive Services Ltd. is hiring for the role of Executive Assistant",
      requirements: [
        "Bachelor’s degree in Business Administration or a related field",
        "Proven experience as an Executive Assistant or similar role",
        "Proficiency in office software (e.g., Microsoft Office Suite)",
        "Strong organizational and multitasking skills",
        "Excellent communication and interpersonal abilities",
        "Ability to handle confidential information with discretion",
        "Attention to detail and accuracy in handling executive tasks",
        "Experience managing executive calendars and scheduling",
        "Ability to prioritize and manage multiple tasks simultaneously",
        "Team-oriented with the ability to work collaboratively",
        "Continuous learning mindset to stay updated on business practices",
      ],

      responsibilities: [
        "Provide high-level administrative support to executives",
        "Manage and coordinate executive calendars, meetings, and travel",
        "Prepare and organize materials for executive meetings",
        "Handle incoming calls, emails, and other communications",
        "Draft and edit executive correspondence and documents",
        "Coordinate and assist in the execution of special projects",
        "Maintain records and files related to executive activities",
        "Assist in the preparation of reports and presentations",
        "Handle sensitive information with confidentiality and professionalism",
        "Contribute to the improvement of administrative processes",
      ],
    },
    {
      id: "25",
      logo: "company12",
      title: "Social Media Manager",
      companyName: "SocialBuzz Inc.",
      impressions: "5678 Impressions",
      deadline: "16 Days Left",
      segment: "Non-Technical",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      status: "LIVE",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "SocialBuzz Inc. Ltd. is hiring for the role of Social Media Manager",
      requirements: [
        "Bachelor’s degree in Marketing, Communication, or a related field",
        "Proven experience as a Social Media Manager or similar role",
        "In-depth knowledge of social media platforms and trends",
        "Experience with social media analytics and reporting tools",
        "Creativity and a passion for creating engaging content",
        "Excellent communication and interpersonal abilities",
        "Ability to develop and implement social media strategies",
        "Familiarity with graphic design and content creation tools",
        "Strong project management and organizational skills",
        "Continuous learning mindset to stay updated on social media trends",
      ],

      responsibilities: [
        "Develop and implement social media strategies to achieve business goals",
        "Create, curate, and manage all published content on social media platforms",
        "Monitor and analyze social media metrics to measure the success of campaigns",
        "Stay updated on industry trends and innovations in social media",
        "Respond to comments and engage with followers on social media channels",
        "Collaborate with internal teams to align social media efforts with overall marketing goals",
        "Manage social media advertising campaigns",
        "Track and report on social media performance and analytics",
        "Stay informed about changes in social media algorithms and adjust strategies accordingly",
        "Contribute to the improvement of social media processes",
      ],
    },
    {
      id: "26",
      logo: "company13",
      title: "Logistics Coordinator",
      companyName: "LogiTech Solutions",
      impressions: "9876 Impressions",
      deadline: "8 Days Left",
      segment: "Non-Technical",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      status: "LIVE",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "LogiTech Solutions is hiring for the role of Logistics Coordinator",
      requirements: [
        "Bachelor’s degree in Business Administration, Logistics, or a related field",
        "Proven experience as a Logistics Coordinator or similar role",
        "Knowledge of logistics and supply chain management principles",
        "Strong organizational and multitasking skills",
        "Excellent communication and interpersonal abilities",
        "Ability to coordinate and manage logistics operations",
        "Familiarity with transportation and shipping regulations",
        "Attention to detail and accuracy in handling logistics tasks",
        "Problem-solving skills to address logistical challenges",
        "Continuous learning mindset to stay updated on logistics trends",
      ],

      responsibilities: [
        "Coordinate and monitor logistics operations to ensure efficiency",
        "Manage and track shipments, deliveries, and inventory",
        "Communicate with suppliers, carriers, and internal teams",
        "Ensure compliance with transportation and shipping regulations",
        "Optimize logistics processes to reduce costs and improve efficiency",
        "Resolve logistical issues and address delays or disruptions",
        "Maintain accurate records of logistics activities",
        "Collaborate with vendors and negotiate transportation rates",
        "Prepare reports on logistics performance and key metrics",
        "Contribute to the improvement of logistics processes",
      ],
    },
    {
      id: "27",
      logo: "company14",
      title: "Legal Assistant",
      companyName: "LegalEase Law Firm",
      impressions: "6543 Impressions",
      deadline: "17 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "LegalEase Law Firm is hiring for the role of Legal Assistant",
      requirements: [
        "Bachelor’s degree in Law, Legal Studies, or a related field",
        "Proven experience as a Legal Assistant or similar role",
        "Familiarity with legal terminology and procedures",
        "Strong organizational and multitasking skills",
        "Excellent communication and interpersonal abilities",
        "Ability to draft legal documents and correspondence",
        "Attention to detail and accuracy in handling legal tasks",
        "Knowledge of legal research and case management",
        "Proficiency in legal software and databases",
        "Continuous learning mindset to stay updated on legal trends",
      ],

      responsibilities: [
        "Assist in drafting and preparing legal documents",
        "Conduct legal research and gather relevant information",
        "Organize and maintain legal files and documentation",
        "Prepare and organize materials for legal proceedings",
        "Assist attorneys in case preparation and management",
        "Communicate with clients, witnesses, and other legal professionals",
        "Manage and update legal databases and records",
        "Schedule and coordinate legal meetings and appointments",
        "Handle administrative tasks to support legal activities",
        "Contribute to the improvement of legal processes",
      ],
    },
    {
      id: "28",
      logo: "company15",
      title: "Fitness Instructor",
      companyName: "FitLife Wellness Center",
      impressions: "7890 Impressions",
      deadline: "19 Days Left",
      segment: "Non-Technical",
      status: "LIVE",
      companyLocation:"Bangalore",
      jobLocation:"Remote/hybrid",
      experience:"2+ years",
      hashtags: ["#Web Development", "#Programmimg"],
      jobDescription:
        "FitLife Wellness Center is hiring for the role of Fitness Instructor",
      requirements: [
        "Certification in Fitness Instruction or related field",
        "Proven experience as a Fitness Instructor",
        "In-depth knowledge of fitness principles and exercise techniques",
        "Strong communication and interpersonal abilities",
        "Ability to create and lead engaging fitness classes",
        "Knowledge of nutrition and wellness principles",
        "Motivational and supportive attitude towards clients",
        "Current CPR and first aid certifications",
        "Continuous learning mindset to stay updated on fitness trends",
      ],

      responsibilities: [
        "Plan and conduct fitness classes and training sessions",
        "Provide guidance on proper exercise techniques and form",
        "Create personalized fitness plans for clients",
        "Monitor and track clients' progress and fitness goals",
        "Promote a positive and inclusive fitness environment",
        "Educate clients on nutrition and healthy lifestyle choices",
        "Demonstrate exercises and assist clients with proper equipment use",
        "Motivate and encourage clients to achieve their fitness goals",
        "Ensure safety and adherence to fitness guidelines",
        "Contribute to the improvement of fitness programs",
      ],
    },
  ];
  const [userInfo, setUserInfo] = useState(null);
  const [isPopupOpen, setIsPopupOpen] = useState(false);
  const [jd, setJd] = useState(null);

  useEffect(() => {
    const storedUserInfo = localStorage.getItem("userInfo");
    if (storedUserInfo) {
      setUserInfo(JSON.parse(storedUserInfo));
    } else {
      setIsPopupOpen(true);
    }
  }, []);

  const saveUserInfo = (info) => {
    localStorage.setItem("userInfo", JSON.stringify(info));
    setUserInfo(info);
    setIsPopupOpen(false);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 w-full sm:w-[500px] md:w-[800px] lg:w-[1000px] xl:w-[1199px] ">
      <div className="flex justify-center items-center h-full">
        <div className="bg-[#F6F8FA] w-full h-full flex flex-col gap-2   ">
          {userInfo && (
            <div className="">
              <div className="w-full flex justify-start mt-2 gap-2 my-2 ">
                <div className="flex-1 ">
                  <SearchBar />
                </div>
                <div className="flex-1 flex justify-end">
                  <button
                    onClick={() => setIsPopupOpen(true)}
                    className=" inline-flex items-center bg-blue-100 text-blue-500 font-semibold py-1 px-4 rounded-full"
                  >
                    <span className="mr-2 text-xs">
                      Smart Search Preference:{localStorage.getItem("userInfo")}
                    </span>
                    <button className="focus:outline-none">
                      <MdEdit />
                    </button>
                  </button>
                </div>
              </div>

              <Filter />
              <div className={`w-full flex gap-4 my-2 `}>
                <JobOptions jobData={jobData} setJobdes={setJd} />
                <JobView jobDetails={jd} />
              </div>
            </div>
          )}
          {isPopupOpen && (
            <div className="w-full h-screen flex justify-center mt-4">
              <ModalComp saveUserInfo={saveUserInfo} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default MainJobContainer;
